# Rasio Dosen dan Mahasiswa

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(readxl)
library(downloadthis)
library(tidyverse)
rasio <- read_excel("static/rasio.xlsx")
aktif <- read_excel("static/aktif.xlsx")
dos_pns <- read_excel("static/SDM_dosen_pns.xlsx")
dos_non <- read_excel("static/SDM_dosen_non_pns.xlsx")
dos <- rbind(dos_non, dos_pns)

mhs <- aktif %>%
  group_by(FAK = toupper(fakultas), PRODI = toupper(prodi), jenjang) %>%
  summarise(mhs = n()) %>%
  filter(FAK != "PASCASARJANA")

dos1 <- dos %>%
  group_by(FAK = toupper(FAK), PRODI = toupper(PRODI)) %>%
  summarise(dos = n())

ratio <- mhs %>%
  left_join(dos1, by = c("FAK", "PRODI")) %>%
  replace( ., is.na(.), 0) %>%
  mutate(rasio = paste("1 :", round(mhs/dos, 0)),
         FAK = case_when(
    FAK == "HUKUM" ~ "1_HUKUM",
    FAK == "FKIP" ~ "2_FKIP",
    FAK == "TEKNIK" ~ "3_TEKNIK",
    FAK == "PERTANIAN" ~ "4_PERTANIAN",
    FAK == "FEB" ~ "5_FEB",
    FAK == "FISIP" ~ "6_FISIP",
    FAK == "PASCASARJANA" ~ "7_PASCASARJANA",
    FAK == "KEDOKTERAN" ~ "8_KEDOKTERAN"
  )) %>%
  arrange(FAK, PRODI)

```

Secara keseluruhan, rasio dosen dan mahasiswa di untirta adalah 1 : `r round(sum(rasio$mahasiswa)/sum(rasio$dosen, na.rm = T), 0)`. Rasio dosen dan mahasiswa ideal untuk rumpun sosial adalah 1 : 45 dan untuk rumpun sains adalah 1 : 30. Berikut adalah rasio dosen dan mahasiswa Universitas Sultan Ageng Tirtayasa di setiap Program Studi.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
rasio <- ratio[,-1]
names(rasio) <- c("Program Studi", "Jenjang", "Mahasiswa", "Dosen", "Rasio")
library(kableExtra)
kable(rasio, row.names = F) %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                latex_options = "scale_down") %>%
  pack_rows("Hukum", 1, 1, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Keguruan dan Ilmu Pendidikan", 2, 19, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Teknik", 20, 26, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Pertanian", 27, 31, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ekonomi dan Bisnis", 32, 39, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ilmu Sosial dan Ilmu Politik", 40, 42, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Kedokteran", 43, 47, label_row_css = "background-color: #666; color: #fff;")


```

```{r echo=FALSE, warning=FALSE, message=FALSE}
### menambahkan tombol Download data untuk tabel di atas

rasio %>%
  download_this(
    output_name = "rasio dosen mhs",
    output_extension = ".xlsx",
    button_label = "Download data",
    button_type = "warning",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

