# Tentang Kami {.unnumbered}

Registrasi dan Statistik adalah salah satu subbagian di bawah Bagian Akademik dan Kemahasiswaan di Biro Akademik, Kemahasiswaan, dan Perencanaan (BAKP) Universitas Sultan Ageng Tirtayasa. Berikut adalah rincian tugas Subbagian Registrasi dan Statistik:

a.  melakukan penyusunan program kerja Subbagian;
b.  melakukan penyusunan pedoman pelaksanaan penerimaan dan registrasi mahasiswa;
c.  melakukan penerimaan mahasiswa baru;
d.  melakukan urusan registrasi mahasiswa;
e.  melakukan penyiapan kartu mahasiswa, kartu rencana studi, kartu hasil studi dan pemberian nomor induk mahasiswa;
f.  melakukan urusan alih program studi;
g.  melakukan urusan cuti akademik mahasiswa;
h.  melakukan pemrosesan pindah mahasiswa dan/atau pengunduran diri mahasiswa;
i.  melakukan penyusunan statistik mahasiswa;
j.  melakukan penyimpanan dan pemeliharaan dokumen Subbagian; dan
k.  melakukan penyusunan laporan Subbagian.

Subbagian Registrasi dan Statistik dikoordinasi oleh seorang Kepala Subbagian dan dibantu oleh 3 orang staf.
